/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyTimer {}
  interface MyTimerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyTimer': Components.MyTimer;
  }

  interface StencilIntrinsicElements {
    'my-timer': Components.MyTimerAttributes;
  }


  interface HTMLMyTimerElement extends Components.MyTimer, HTMLStencilElement {}
  var HTMLMyTimerElement: {
    prototype: HTMLMyTimerElement;
    new (): HTMLMyTimerElement;
  };

  interface HTMLElementTagNameMap {
    'my-timer': HTMLMyTimerElement
  }

  interface ElementTagNameMap {
    'my-timer': HTMLMyTimerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
